#!/bin/sh

cd `dirname "$0"`


if [ -z "$1" -o ! -e "./$1" ]; then 
	echo "Usage: $0 <screen-rc-file>" >&2
       	echo " with one of the following options:" >&2
	ls screenrc-* | xargs -I x echo "  - " x >&2
	exit 1
fi

if [ ! -f "tracker-profile.sh" ]; then
	echo "tracker-profile.sh not found in `pwd`! " >&2
	if [ -z "$CRS_TRACKER" -o -z "$CRS_TOKEN" -o -z "$CRS_SECRET" ]; then
		echo 'Env vars CRS_TRACKER, CRS_TOKEN or CRS_SECRET are also empty.' >&2
		echo 'Please create tracker-profile.sh or define env vars!' >&2
		exit 1
	fi
fi

screen -c ./$1
